# Generated by Django 4.1.2 on 2022-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Formula_1',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Formula_2',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Formula_3',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='law_1',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='law_2',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='law_3',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
