# Generated by Django 4.1.2 on 2022-11-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_items_formula_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Formula_8',
        ),
    ]
