# Generated by Django 4.1.2 on 2022-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_items_param'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Param',
            new_name='Param_1',
        ),
        migrations.AddField(
            model_name='items',
            name='Param_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Param_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
